### ISSUE TITLE
just a blueprint :)

### ISSUE THREAD

**Issue by sancio6** [kotelnik/plasma-applet-active-window-control#1]
Hi! First of all, let me tell you that applet works really fine in plasma 5 and helps me maximize my workspace! I'd like to propose a simple blueprint, just a stilish thing: when no window is active, it would be nice to see, instead of the "No active window" string, maybe something like "Plasma Desktop" or similar. Ok, it would be a little "Ubuntous", but I really think that could make your applet a little more pleasant! Aniway, thanks for your work!

**Comment by kotelnik** [comment]
Hello sancio, thanks very much for your feedback. I think your proposal is a good idea and since I didn't come up with anything better, I just pushed the "Plasma Desktop" text change. I will also be happy for any future suggestions (and/or criticism) I recieve :) Next feature I want to add is support for some kind of menu (menu-button or unity-like menu), but it will take some time...
